#!/bin/bash
DATASET=/home/ichlubna/Downloads/frames
DATASET_SIZE_DIRS=("ten" "five" "full")
DATASET_SIZE_DIRS_LENGTH=$(( ${#DATASET_SIZE_DIRS[@]}-1 ))
FOCUSES=(3350 900 1000 15000 3900)
FULL_DISPL=(0.0027 0.0006 0.002 0.007 0.005)
FIFTH_DISPL=(0.01 0.004 0.011 0.04 0.065)
TENTH_DISPL=(0.02 0.009 0.02 0.07 0.082)
DISPL=("${TENTH_DISPL[@]}" "${FIFTH_DISPL[@]}" "${FULL_DISPL[@]}")
DATASET_DIRS=("bunny" "pavilion" "sand" "cars" "class")
DATASET_DIRS_LENGTH=$(( ${#DATASET_DIRS[@]}-1 ))
for j in $(seq 0 $DATASET_DIRS_LENGTH); do
    DIR=${DATASET_DIRS[j]}
    for i in $(seq 0 $DATASET_SIZE_DIRS_LENGTH); do
    SIZE=${DATASET_SIZE_DIRS[i]}
        ./visualQuality $DATASET"/"$DIR"/"$SIZE "./"$DIR"-"$SIZE ${DISPL[$(( $j+$i*($DATASET_DIRS_LENGTH+1) ))]} ${FOCUSES[j]}
    done
done


